package com.registration;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.util.concurrent.TimeUnit;

public class EnterRegGrabDetails {
    private WebDriver driver;
    JavascriptExecutor js;

    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
    }

    public void tearDown() {
        driver.quit();
    }

    public String[] enterRegGrabDetails(String input) {
        String[] output = new String[5];
        output[0] = input;
        driver.get("https://cartaxcheck.co.uk/");
        driver.manage().window().setSize(new Dimension(1374, 744));
        driver.findElement(By.id("vrm-input")).click();
        driver.findElement(By.id("vrm-input")).sendKeys(input);
        driver.findElement(By.cssSelector(".jsx-1164392954")).click();
        js.executeScript("window.scrollTo(0,297)");
        js.executeScript("window.scrollTo(0,1000)");
        try {
            Thread.sleep(2000);
        }
        catch(InterruptedException e7) {
            e7.printStackTrace();
        }
        {
            WebElement element = driver.findElement(By.xpath("//dl[2]/dd"));
            String make = element.getText();
            output[1] = make;
        }
        {
            WebElement element = driver.findElement(By.xpath("//dl[3]/dd"));
            String model = element.getText();
            output[2] = model;
        }
        {
            WebElement element = driver.findElement(By.xpath("//dl[4]/dd"));
            String color = element.getText();
            output[3] = color;
        }
        {
            WebElement element = driver.findElement(By.xpath("//dl[5]/dd"));
            String year = element.getText();
            output[4] = year;
        }
        return output;
    }
}
